# ~/.config/hypr/hyprlock.conf

general {
    grace = 30
    hide_cursor = true
    no_fade_in = false
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 10
    noise = 0.02
    contrast = 0.9
    brightness = 0.35
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 5
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = true
    rounding = 0
    outer_color = rgb(f9f9f9)
    inner_color = rgb(bfbfbf)
    font_color = rgb(f9f9f9)
    check_color = rgb(a6e3a1)
    fail_color = rgb(f9f9f9)
    placeholder_text = <i>put yo password unc...</i>
    hide_input = false
    position = 20, 20
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:60000] ~/.local/bin/hyprlock-calendar
    color = rgb(a6adc5)
    font_size = 20
    font_family = imd grotesk
    position = -20, -380
    halign = right
    valign = top
}

label {
    monitor =
    text = $TIME
    color = rgb(f9f9f9)
    font_size = 300
    font_family = IMD grotesk heavy
    position = 0, 0
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:5000] bat=$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null | head -1); ram=$(free | awk '/^Mem:/{printf "%.0f", $3/$2*100}'); echo "  ${ram}%    ${bat:-N/A}%"
    color = rgb(6c7086)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -20, -335
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgb(a6adc5)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -400, -335
    halign = right
    valign = top
}
